# Version of docker-compose
version: '2.1'

# Containers we are going to run
services:
  # Our Phoenix container
  versioning_ms:
    # The build parameters for this container.
    build: .
      # Here we define that it should build from the current directory
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: versioning
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: versioning_db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The versioning_db container needs to be started before we start this container
      - versioning_db
  versioning_db:
    # We use the predefined Postgres image
    image: postgres:10
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: